version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    working_dir: /home/node/src
    volumes:
      - ./app:/home/node
    command: /bin/bash
    tty: true
    ports:
      - 3000:3000